### ISSUE TITLE
bogus blocksize/samplerate assumptions

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#22]
looking through the code, i noticed that fftease wrongly calculates the signal vectorsize and samplerate.

it uses `sys_getblksize()` and `sys_getsr()` which really give the *global* blocksize resp. samplerate.
this means that `sys_getblksize()` will always return `64` (unless somebody re-compiled Pd with a different default blocksize) and `sys_getsr()` will return whatever the user set in the audio settings.

now in Pd, each patch can have a different blocksize, and each block can run at a different samplerate (re-sampling the parent patch via a power-of-two factor).

e.g. putting a `[block~ 1024 1 2]` in a subpatch, will change the **local**  blocksize to `1024` and the *local* samplerate to 88200 (assuming that the global samplerate is 44.1kHz).
however `sys_getblksize()` will still return `64`, and `sys_getsr()` will return 44100.

the one and only proper way to get the *local* blocksize, is by using `t_signal.s_n`.
to get the *local* samplerate, use `t_signal.s_sr` (a `t_float` value!).

note: unfortunately `t_signal.s_sr` takes both the *overlap* factor and the *resampling* factor into account (`s_sr = parent.s_sr * overlap * upsample`)...

**Comment by ericlyon** [comment]
Sounds like the blocksize is an easy fix. How do other Pd objects deal with SR changes inside a block~ subpatch?

**Comment by umlaeute** [comment]
probably best check one of the objects that come with Pd, e.g. `[bonk~]`:

https://github.com/pure-data/pure-data/blob/c8af32521e9c723bfb2c83fbdd798b30461876f7/extra/bonk%7E/bonk%7E.c#L814-L820

seems to simply ignore the overlap factor, and uses `t_signal.s_sr` as is.

**Comment by ericlyon** [comment]
Might as well use t_signal for both blocksize and sr, and check if it breaks anything.

**Comment by ericlyon** [comment]
This issue revealed a problem in the Max/MSP version - downsampling in poly~ (similar to block~) results in unstable behavior, and possible white noise blasts. So please be careful with volume levels when investigating block~ operations. The fix in Max is to set
fft-> Nw = fft->N; in the initialization method. So far, I've only tested one MSP object, pvoc~. I'll investigate if this is a problem for the other objects, though it likely will be.

Nw gets initialized in fftease_set_fft_buffers() so I'm not yet sure why this issue is showing up in poly~. Will investigate. For now, it won't hurt to pre-initialize the Nw (window size) in the initialization methods.

**Comment by umlaeute** [comment]
`[block~]` seems to initialize it's buffers with `sys_getsr()` (and the like).
the values then get updated in the `dsp` callback.

**Comment by ericlyon** [comment]
I could not replicate the pvoc~/poly~ issue with other FFTease externals in Max. For now, I advise caution when testing FFTease objects with block~, and please report any anomalous behavior. 

That issue aside, the recommended code improvement in this thread sounds like a good idea.
