### ISSUE TITLE
mindwarp~ segfaults

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#30]
basically re-opening #24 as a new issue, as it still crashes.

so i looked at the code, and `do_mindwarp` looks very suspicious:

https://github.com/ericlyon/pd-fftease/blob/c7726fc1a27c84e58b8e0122549bbbf3c9758518/mindwarp%7E.c#L214-L224

so we access the `newChannel` and `channelOne` arrays at `i+j` with `i=0..N` and `j=0..(shapeWidth*2) = 0..(N2*2) = 0..N` (in the worst case), which means that the we will eventually access `newChannel[2N]`, with `N` being:
https://github.com/ericlyon/pd-fftease/blob/c7726fc1a27c84e58b8e0122549bbbf3c9758518/mindwarp%7E.c#L120

however, `newChannel` is allocated as:

https://github.com/ericlyon/pd-fftease/blob/c7726fc1a27c84e58b8e0122549bbbf3c9758518/mindwarp%7E.c#L78

so the code basically access an array af size `N+1` at position `2N`.
unless N==1, this is an out of bound access.

the situtation is the similar for `channelOne` (although a bit harder to spot):
- `channelOne` is an alias for `fft->channel` https://github.com/ericlyon/pd-fftease/blob/c7726fc1a27c84e58b8e0122549bbbf3c9758518/mindwarp%7E.c#L118
- `fft->channel` holds `fft->N+2` floats: https://github.com/ericlyon/pd-fftease/blob/c7726fc1a27c84e58b8e0122549bbbf3c9758518/fftease_utilities.c#L151-L152

**Comment by umlaeute** [comment]
as a quick test: if i comment out the actual [shaping code](https://github.com/ericlyon/pd-fftease/blob/master/mindwarp%7E.c#L214-L267), i get no more crashes.

obviously, this breaks the functionality of the object.

**Comment by ericlyon** [comment]
Nice catch, thanks. The solution will be to allocate sufficient memory for worst case access for all arrays currently subject to this out of bounds bug. Please give that a try, and submit a PR if that eliminates the crashes, while maintaining object functionality.

**Comment by umlaeute** [comment]
that's easy enough with `newChannel`, but i'm not so sure whether that's a good idea with `fft->channel`.

**Comment by ericlyon** [comment]
> that's easy enough with `newChannel`, but i'm not so sure whether that's a good idea with `fft->channel`.

Agreed. A better solution would be to copy fft->channel to a new array that has sufficient memory, ideally stored in the object structure. Please let me know if you'd like to try that. Otherwise, I can update the code, but since I'm working on macOS, I won't be able to confirm when the problem has been fixed. Someone would have to try my solution on Linux or Windows.

**Comment by umlaeute** [comment]
i can try that.

as you know the code better than me: would i just set the extra elements to zero?


something like this?

~~~
static void do_mindwarp(t_mindwarp *x) {
    // ...
    fftease_fold(fft);
    fftease_rdft(fft,FFT_FORWARD);
    fftease_leanconvert(fft);

    for(i=0; i<N; i++)
         channelOne[i] = fft->channel[i];
    for(i=0; i<N; i++)
         channelOne[N+i] = 0.;

    // ... here comes the hard work ...
    for(i=0; i<N; i++)
         fft->channel[i] = channelOne[i];

    fftease_leanunconvert(fft);
    fftease_rdft(fft,FFT_INVERSE);
    fftease_overlapadd(fft);
}

**Comment by ericlyon** [comment]
Yes, that looks good, thanks! If I understand your solution, *channelOne would now be an object structure variable, rather than assigned through dereferencing, as in the current code. So, there would be the additional work of adding *channelOne to the object structure, allocating memory for it in mindwarp_init(), and deferencing *channelOne from the object structure, rather than from fft->channel as such:

t_float *channelOne = x->channelOne;

Finally, *channelOne would need to be freed in mindwarp_free().

Please give that a try, and if it works, I'll integrate a PR with your new code.
